
include:
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: nice_corne_left
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: nice_corne_right

  - board: nice_nano_v2
    shield: corne_left_peripheral 
    artifact-name: nice_corne_left_peripheral

  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    artifact-name: nice_corne_dongle_pro_micro
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro dongle_display
    artifact-name: nice_corne_dongle_oled

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset

