# This file generates the GitHub Actions matrix
---
include:
  # sweep
  - board: nice_nano_v2
    shield: sweep_dongle dongle_display
  - board: nice_nano_v2
    shield: sweep_left
  - board: nice_nano_v2
    shield: sweep_left
  - board: nice_nano_v2
    shield: sweep_right


  - board: nice_nano_v2
    shield: sweep_dongle dongle_display
  - board: nice_nano_v2
    shield: sweep_left

  # reset
  - board: nice_nano_v2
    shield: settings_reset
